feat: Add fr-FR translation and begin translation with dashboard and clients
CIDgravity/CIDgravity-localization pull request #3
Opened 2022-09-19 08:19 UTC by FlorianRuen

Closes #2

2022-09-19 08:47 UTC, nicobao requested changes
Nice!
You need to add `clients.json` too

2022-09-19 16:52 UTC, nicobao requested changes
Can you push `.prettierrc.json` and the update `package.json` and `package-lock.json`?

2022-09-19 16:52 UTC, nicobao commented on cidgravity/locales/dev/clientsContainer.json
> +      "deals_one": "1 deal",
Replace to:
```
"deals_zero": "{{count}} deal",
"deals_one": "{{could}} deal"
```

2022-09-19 16:52 UTC, nicobao commented on cidgravity/locales/dev/clientsContainer.json
> +      "deals_one": "1 deal",
```
"deals_zero": "{{count}} deal",
"deals_one": "{{could}} deal"
```

2022-09-19 16:52 UTC, nicobao commented on cidgravity/locales/dev/clientsContainer.json
> +  "toasts": {
Julien wanted to rename `toasts` to `notifications`

2022-09-19 16:52 UTC, nicobao commented on cidgravity/locales/dev/common.json
> +      "B_one": "1 B",
replace here too

2022-09-19 16:52 UTC, nicobao commented on cidgravity/locales/dev/common.json
> +      "GiB_one": "1 GiB",
replace here too

2022-09-19 16:52 UTC, nicobao commented on cidgravity/locales/dev/common.json
> +      "TiB_one": "1 TiB",
replace here too

2022-09-19 16:52 UTC, nicobao commented on cidgravity/locales/dev/common.json
> +      "MiB_one": "1 MiB",
replace here too

2022-09-20 07:11 UTC, FlorianRuen commented on cidgravity/locales/dev/common.json
> +      "MiB_one": "1 MiB",
Done

2022-09-20 07:11 UTC, FlorianRuen commented on cidgravity/locales/dev/common.json
> +      "TiB_one": "1 TiB",
Done

2022-09-20 07:11 UTC, FlorianRuen commented on cidgravity/locales/dev/common.json
> +      "B_one": "1 B",
Done

2022-09-20 07:12 UTC, FlorianRuen commented on cidgravity/locales/dev/clientsContainer.json
> +  "toasts": {
Done

2022-09-20 07:12 UTC, FlorianRuen commented on cidgravity/locales/dev/clientsContainer.json
> +      "deals_one": "1 deal",
Done

2022-09-20 07:12 UTC, FlorianRuen commented on cidgravity/locales/dev/clientsContainer.json
> +      "deals_one": "1 deal",
Done

2022-09-20 07:13 UTC, FlorianRuen commented
> Nice! You need to add `clients.json` too

Why clients.json ? I don't have a file with that name

2022-09-20 07:14 UTC, FlorianRuen commented
> Can you push `.prettierrc.json` and the update `package.json` and `package-lock.json`?

Good point, I hadn't noticed that they hadn't been added to the commit

2022-09-20 07:55 UTC, nicobao approved these changes
LGTM

2022-09-20 07:57 UTC, merged

2022-10-11 16:10 UTC, CIDgravity-weblate commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@cidgravity/cidgravity-locales/v/1.0.0)
- [GitHub release](https://github.com/CIDgravity/CIDgravity-localization/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: